struct bytesOutputWithData{	// data object for files, stores content and its size in bytes
	unsigned long long size;
	char* bufferPointer;
};

struct bitsInByte{		// data object for bits, stores bits generated by byteToBit()
	char bits[8];
};

bitsInByte byteToBit(char byteIn); // makes bits out of bytes, welp
bytesOutputWithData fileToBytes(char* fileName, char* bytesOut); // opens file, reads its content, closes file
char* unsignedlonglongToFormattedHex(unsigned long long longlongIn); // formats bytesOutputWithData.size to output address section (in hex)
char* buildAndPrintLine(char* bitsA, char* bitsB, unsigned long long address); // makes line with data and prints it

